#!/usr/bin/env python3
"""Generate MFL Unicode range tables for \\p{L}, \\p{N} and \\s.

The BPE pretokenizer regexes (cl100k_base / o200k_base) are defined in terms of
Unicode general categories. POSIX ERE -- all machin's regex_* builtins offer --
cannot express \\p{L}. So we bake the ranges into sorted flat arrays and binary
search them at runtime. Output is deterministic: regenerating on the same Python
Unicode version reproduces the file byte for byte.
"""
import sys, unicodedata

MAX = 0x110000


def ranges_for(pred):
    out, start = [], None
    for cp in range(MAX):
        if pred(cp):
            if start is None:
                start = cp
        else:
            if start is not None:
                out.append((start, cp - 1))
                start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def cat(cp):
    return unicodedata.category(chr(cp))


# \p{L} -- Lu Ll Lt Lm Lo
is_letter = lambda cp: cat(cp).startswith("L")
# \p{N} -- Nd Nl No
is_number = lambda cp: cat(cp).startswith("N")
# regex \s (Unicode): White_Space property == Zs/Zl/Zp + the ASCII controls + NEL
WS_EXTRA = {0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x85}
is_space = lambda cp: cp in WS_EXTRA or cat(cp) in ("Zs", "Zl", "Zp")
# The o200k_base pattern only ever uses two *combined* letter classes:
#   [\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}]  and  [\p{Ll}\p{Lm}\p{Lo}\p{M}]
# Emitting them pre-unioned is both smaller and one binary search instead of five.
UPPERISH = ("Lu", "Lt", "Lm", "Lo", "Mn", "Mc", "Me")
LOWERISH = ("Ll", "Lm", "Lo", "Mn", "Mc", "Me")
is_upperish = lambda cp: cat(cp) in UPPERISH
is_lowerish = lambda cp: cat(cp) in LOWERISH


def emit(name, rs):
    """Flat [lo0,hi0, lo1,hi1, ...] -- one pair per range, binary searched."""
    flat = []
    for lo, hi in rs:
        flat += [lo, hi]
    body = ", ".join(str(x) for x in flat)
    return "var %s = []int{%s}\n" % (name, body)


def main():
    tables = [
        ("uni_letter", is_letter),
        ("uni_number", is_number),
        ("uni_space", is_space),
        ("uni_upperish", is_upperish),
        ("uni_lowerish", is_lowerish),
    ]
    out = [
        "// GENERATED by tools/gen_unicode.py -- do not edit.",
        "// Unicode %s general-category ranges for the BPE pretokenizer." % unicodedata.unidata_version,
        "",
    ]
    for name, pred in tables:
        rs = ranges_for(pred)
        out.append("// %s: %d ranges" % (name, len(rs)))
        out.append(emit(name, rs))
        print("%-12s %5d ranges" % (name, len(rs)), file=sys.stderr)
    open(sys.argv[1], "w").write("\n".join(out))


main()
